# =============================================================================
#  GENERIC FILE LAUNCHER — Generated by MaxTechFix Software Protector v1.0
#  Developer: Zulfiqar Ali  |  www.maxtechfix.com
# =============================================================================
import sys as _sys, os as _os, json as _json, base64 as _b64, tempfile as _tf
import hashlib as _hl, hmac as _hmac, uuid as _uuid, datetime as _dt
import subprocess as _sub

_SP_APP_NAME       = "###APP_NAME###"
_SP_APP_ID         = "###APP_ID###"
_SP_TRIAL_DAYS     = ###TRIAL_DAYS###
_SP_ENCRYPTED_FILE = r"###ENCRYPTED_FILE###"
_SP_ORIG_FILENAME  = "###ORIGINAL_FILENAME###"
_SP_ENC_KEY_STR    = "###ENCRYPTION_KEY###"
_SP_DATA_DIR       = _os.path.join(_os.path.expanduser("~"), ".sp_data")
_SP_LIC_FILE       = _os.path.join(_SP_DATA_DIR, f"{_SP_APP_ID}.lic")
_SP_TR_FILE        = _os.path.join(_SP_DATA_DIR, f"{_SP_APP_ID}.tr")
_SP_SECRET         = "MaxTechFix_License_Secret_ZulfiqarAli_2024"
_SP_PROT_KEY       = _hl.sha256(b"MaxTechFix_SoftwareProtector_2024_ZulfiqarAli").digest()
_SP_FILE_KEY       = _hl.sha256(_SP_ENC_KEY_STR.encode()).digest()
_SP_CONTACT        = "WhatsApp: 00923411337788  |  Email: redsky991@hotmail.com"

def _sp_xor(d, k):
    return bytes(b ^ k[i % len(k)] for i, b in enumerate(d))

def _sp_enc(data):
    return _b64.urlsafe_b64encode(_sp_xor(_json.dumps(data).encode(), _SP_PROT_KEY)).decode()

def _sp_dec(s):
    try:
        return _json.loads(_sp_xor(_b64.urlsafe_b64decode(s.encode()), _SP_PROT_KEY).decode())
    except Exception:
        return {}

def _sp_read(path):
    try:
        with open(path) as f: return _sp_dec(f.read())
    except Exception:
        return {}

def _sp_write(path, data):
    _os.makedirs(_SP_DATA_DIR, exist_ok=True)
    with open(path, "w") as f: f.write(_sp_enc(data))

def _sp_hwid():
    mac = _uuid.getnode()
    raw = ":".join(format(mac, "012x")[i:i+2] for i in range(0, 12, 2))
    h = _hl.sha256(raw.encode()).hexdigest()[:16].upper()
    return "-".join(h[i:i+4] for i in range(0, 16, 4))

def _sp_valid(email, hwid, key):
    raw = f"{email.lower().strip()}:{hwid.upper().replace('-','')}"
    sig = _hmac.new(_SP_SECRET.encode(), raw.encode(), _hl.sha256).hexdigest()
    return _hmac.compare_digest(key.replace("-","").upper(), sig[:16].upper())

def _sp_trial_choice_dialog(days_left):
    hwid = _sp_hwid(); result = [False]
    try:
        import tkinter as tk; import tkinter.font as tkfont
        root = tk.Tk(); root.title(f"Trial Version — {_SP_APP_NAME}")
        root.configure(bg="#0f172a"); root.geometry("520x380")
        root.resizable(False, False); root.eval("tk::PlaceWindow . center")
        f_t = tkfont.Font(size=14, weight="bold"); f_l = tkfont.Font(size=10)
        f_m = tkfont.Font(size=10)

        choice_frm = tk.Frame(root, bg="#0f172a"); choice_frm.pack(fill="both", expand=True)
        tk.Label(choice_frm,
                 text=f"⏳ Trial Version  —  {days_left} of {_SP_TRIAL_DAYS} days remaining",
                 font=f_t, bg="#0f172a", fg="#f59e0b").pack(pady=(28, 4))
        tk.Label(choice_frm, text=f'You are running  "{_SP_APP_NAME}"  in trial mode.',
                 font=f_l, bg="#0f172a", fg="#94a3b8").pack(pady=(0, 6))
        frm = tk.Frame(choice_frm, bg="#1e293b"); frm.pack(fill="x", padx=36, pady=4)
        tk.Label(frm, text="Your Hardware ID:", font=f_l, bg="#1e293b", fg="#94a3b8").pack(anchor="w", padx=12, pady=(10, 0))
        tk.Entry(frm, textvariable=tk.StringVar(value=hwid), font=f_m, bg="#0f172a", fg="#6366f1",
                 relief="flat", state="readonly", readonlybackground="#0f172a", width=24).pack(padx=12, pady=(2, 10))
        btn_frm = tk.Frame(choice_frm, bg="#0f172a"); btn_frm.pack(pady=20)

        def run_trial():
            result[0] = True; root.destroy()

        def show_register():
            choice_frm.pack_forget(); reg_frm.pack(fill="both", expand=True); root.geometry("520x440")

        tk.Button(btn_frm, text="▶  Run as Trial Version", font=f_l,
                  bg="#f59e0b", fg="#ffffff", relief="flat", cursor="hand2",
                  activebackground="#fbbf24", activeforeground="#ffffff",
                  padx=20, pady=8, command=run_trial).pack(side="left", padx=8)
        tk.Button(btn_frm, text="🔑  Register Full Version", font=f_l,
                  bg="#6366f1", fg="#ffffff", relief="flat", cursor="hand2",
                  activebackground="#818cf8", activeforeground="#ffffff",
                  padx=20, pady=8, command=show_register).pack(side="left", padx=8)
        tk.Label(choice_frm, text=f"To register:  {_SP_CONTACT}",
                 font=f_l, bg="#0f172a", fg="#475569").pack(pady=(0, 10))

        reg_frm = tk.Frame(root, bg="#0f172a")
        tk.Label(reg_frm, text="🔑 Register Full Version", font=f_t,
                 bg="#0f172a", fg="#6366f1").pack(pady=(28, 4))
        tk.Label(reg_frm, text=f'Activate  "{_SP_APP_NAME}"  with your license key.',
                 font=f_l, bg="#0f172a", fg="#94a3b8").pack(pady=(0, 4))
        tk.Label(reg_frm,
                 text=f"Contact:  {_SP_CONTACT}",
                 font=f_l, bg="#0f172a", fg="#f59e0b").pack(pady=(0, 8))
        frm2 = tk.Frame(reg_frm, bg="#0f172a"); frm2.pack(fill="x", padx=36, pady=4)
        email_e = key_e = None
        for txt in ("Email Address:", "License Key:"):
            tk.Label(frm2, text=txt, font=f_l, bg="#0f172a", fg="#94a3b8").pack(anchor="w", pady=(8, 2))
            e = tk.Entry(frm2, font=f_l, bg="#1e293b", fg="#f1f5f9", relief="flat", bd=4, insertbackground="#f1f5f9")
            e.pack(fill="x", ipady=6)
            if txt.startswith("Email"): email_e = e
            else: key_e = e
        sv = tk.StringVar()
        tk.Label(reg_frm, textvariable=sv, font=f_l, bg="#0f172a", fg="#ef4444").pack(pady=(4, 0))
        def activate():
            em = email_e.get().strip(); k = key_e.get().strip()
            if not em or not k: sv.set("Please fill in both fields."); return
            if _sp_valid(em, hwid, k):
                _sp_write(_SP_LIC_FILE, {"email": em, "key": k}); result[0] = True; root.destroy()
            else: sv.set("❌  Invalid license key.")
        tk.Button(reg_frm, text="  Activate License  ", font=f_l, bg="#6366f1", fg="#ffffff",
                  relief="flat", cursor="hand2", activebackground="#818cf8",
                  command=activate).pack(pady=14)
        def back_to_choice():
            reg_frm.pack_forget(); choice_frm.pack(fill="both", expand=True); root.geometry("520x380")
        tk.Button(reg_frm, text="← Back", font=f_l, bg="#334155", fg="#94a3b8",
                  relief="flat", cursor="hand2", activebackground="#475569",
                  command=back_to_choice).pack(pady=(0, 10))
        root.mainloop()
    except Exception: pass
    return result[0]

def _sp_expired_dialog():
    hwid = _sp_hwid(); result = [False]
    try:
        import tkinter as tk; import tkinter.font as tkfont
        root = tk.Tk(); root.title(f"License Required — {_SP_APP_NAME}")
        root.configure(bg="#0f172a"); root.geometry("520x440")
        root.resizable(False, False); root.eval("tk::PlaceWindow . center")
        f_t = tkfont.Font(size=14, weight="bold"); f_l = tkfont.Font(size=10)
        tk.Label(root, text="🔒 Trial Expired", font=f_t, bg="#0f172a", fg="#ef4444").pack(pady=(28,4))
        tk.Label(root, text=f'Trial for "{_SP_APP_NAME}" has expired.', font=f_l,
                 bg="#0f172a", fg="#94a3b8").pack(pady=(0,18))
        frm = tk.Frame(root, bg="#1e293b"); frm.pack(fill="x", padx=36, pady=4)
        tk.Label(frm, text="Your Hardware ID:", font=f_l, bg="#1e293b", fg="#94a3b8").pack(anchor="w", padx=12, pady=(10,0))
        tk.Entry(frm, textvariable=tk.StringVar(value=hwid), font=f_l, bg="#0f172a",
                 fg="#6366f1", relief="flat", state="readonly", readonlybackground="#0f172a",
                 width=24).pack(padx=12, pady=(2,10))
        frm2 = tk.Frame(root, bg="#0f172a"); frm2.pack(fill="x", padx=36, pady=8)
        email_e = key_e = None
        for txt in ("Email Address:", "License Key:"):
            tk.Label(frm2, text=txt, font=f_l, bg="#0f172a", fg="#94a3b8").pack(anchor="w", pady=(8,2))
            e = tk.Entry(frm2, font=f_l, bg="#1e293b", fg="#f1f5f9", relief="flat", bd=4,
                         insertbackground="#f1f5f9"); e.pack(fill="x", ipady=6)
            if txt.startswith("Email"): email_e = e
            else: key_e = e
        sv = tk.StringVar()
        tk.Label(root, textvariable=sv, font=f_l, bg="#0f172a", fg="#ef4444").pack(pady=(4,0))
        def activate():
            em = email_e.get().strip(); k = key_e.get().strip()
            if not em or not k: sv.set("Please fill in both fields."); return
            if _sp_valid(em, hwid, k):
                _sp_write(_SP_LIC_FILE, {"email": em, "key": k}); result[0] = True; root.destroy()
            else: sv.set("❌  Invalid license key.")
        tk.Button(root, text="  Activate License  ", font=f_l, bg="#6366f1", fg="#ffffff",
                  relief="flat", cursor="hand2", command=activate).pack(pady=14)
        tk.Label(root,
                 text=f"To register:  {_SP_CONTACT}",
                 font=f_l, bg="#0f172a", fg="#475569").pack(pady=(0,10))
        root.mainloop()
    except Exception: pass
    return result[0]

def _sp_check():
    hwid = _sp_hwid()
    lic = _sp_read(_SP_LIC_FILE)
    if lic.get("email") and lic.get("key") and _sp_valid(lic["email"], hwid, lic["key"]):
        return True
    trial = _sp_read(_SP_TR_FILE)
    if not trial.get("install_date"):
        trial = {"install_date": _dt.datetime.now().isoformat()}
        _sp_write(_SP_TR_FILE, trial)
    install_dt = _dt.datetime.fromisoformat(trial["install_date"])
    days_used = (_dt.datetime.now() - install_dt).days
    days_left = max(0, _SP_TRIAL_DAYS - days_used)
    if days_left > 0:
        return _sp_trial_choice_dialog(days_left)
    return _sp_expired_dialog()

if not _sp_check():
    _sys.exit(0)

# Decrypt and open the protected file
with open(_SP_ENCRYPTED_FILE, "r") as _f:
    _enc = _b64.b64decode(_f.read())
_dec = bytes(b ^ _SP_FILE_KEY[i % len(_SP_FILE_KEY)] for i, b in enumerate(_enc))
_tmp = _tf.NamedTemporaryFile(delete=False, suffix=_os.path.splitext(_SP_ORIG_FILENAME)[1])
_tmp.write(_dec); _tmp.close()

import platform as _pl
if _pl.system() == "Windows":
    _os.startfile(_tmp.name)
elif _pl.system() == "Darwin":
    _sub.run(["open", _tmp.name])
else:
    _sub.run(["xdg-open", _tmp.name])
