# =============================================================================
#  SOFTWARE PROTECTION LAYER
#  Generated by MaxTechFix Software Protector v1.0
#  Developer: Zulfiqar Ali  |  www.maxtechfix.com
#  DO NOT MODIFY THIS SECTION
# =============================================================================
import sys as _sys, os as _os, json as _json, base64 as _b64
import hashlib as _hl, hmac as _hmac, uuid as _uuid, datetime as _dt
import subprocess as _sp

# ── App configuration ────────────────────────────────────────────────────────
_SP_APP_NAME    = "###APP_NAME###"
_SP_APP_ID      = "###APP_ID###"
_SP_TRIAL_DAYS  = ###TRIAL_DAYS###
_SP_DATA_DIR    = _os.path.join(_os.path.expanduser("~"), ".sp_data")
_SP_LIC_FILE    = _os.path.join(_SP_DATA_DIR, f"{_SP_APP_ID}.lic")
_SP_TR_FILE     = _os.path.join(_SP_DATA_DIR, f"{_SP_APP_ID}.tr")
_SP_SECRET      = "MaxTechFix_License_Secret_ZulfiqarAli_2024"
_SP_ENC_KEY     = _hl.sha256(b"MaxTechFix_SoftwareProtector_2024_ZulfiqarAli").digest()

# ── Crypto helpers ────────────────────────────────────────────────────────────
def _sp_xor(d, k):
    return bytes(b ^ k[i % len(k)] for i, b in enumerate(d))

def _sp_enc(data):
    return _b64.urlsafe_b64encode(_sp_xor(_json.dumps(data).encode(), _SP_ENC_KEY)).decode()

def _sp_dec(s):
    try:
        return _json.loads(_sp_xor(_b64.urlsafe_b64decode(s.encode()), _SP_ENC_KEY).decode())
    except Exception:
        return {}

def _sp_read(path):
    try:
        with open(path) as f:
            return _sp_dec(f.read())
    except Exception:
        return {}

def _sp_write(path, data):
    _os.makedirs(_SP_DATA_DIR, exist_ok=True)
    with open(path, "w") as f:
        f.write(_sp_enc(data))

# ── Hardware ID ───────────────────────────────────────────────────────────────
def _sp_hwid():
    mac = _uuid.getnode()
    raw = ":".join(format(mac, "012x")[i:i+2] for i in range(0, 12, 2))
    h = _hl.sha256(raw.encode()).hexdigest()[:16].upper()
    return "-".join(h[i:i+4] for i in range(0, 16, 4))

# ── License validation ────────────────────────────────────────────────────────
def _sp_valid(email, hwid, key):
    raw = f"{email.lower().strip()}:{hwid.upper().replace('-','')}"
    sig = _hmac.new(_SP_SECRET.encode(), raw.encode(), _hl.sha256).hexdigest()
    return _hmac.compare_digest(key.replace("-","").upper(), sig[:16].upper())

# ── Trial / License GUI ───────────────────────────────────────────────────────
def _sp_trial_notice(days_left):
    try:
        import tkinter as tk
        from tkinter import messagebox
        r = tk.Tk(); r.withdraw()
        messagebox.showwarning(
            f"⚠️ Trial – {_SP_APP_NAME}",
            f"TRIAL VERSION  –  {days_left} of {_SP_TRIAL_DAYS} days remaining.\n\n"
            f"Purchase a license at:\n  www.maxtechfix.com\n\n"
            f"Your Hardware ID:\n  {_sp_hwid()}"
        )
        r.destroy()
    except Exception:
        pass

def _sp_expired_dialog():
    hwid = _sp_hwid()
    result = [False]
    try:
        import tkinter as tk
        from tkinter import messagebox

        root = tk.Tk()
        root.title(f"License Required — {_SP_APP_NAME}")
        root.configure(bg="#0f172a")
        root.geometry("520x440")
        root.resizable(False, False)
        root.eval("tk::PlaceWindow . center")

        # Fonts
        try:
            f_title = tk.font.Font(family="Segoe UI", size=14, weight="bold")
            f_label = tk.font.Font(family="Segoe UI", size=10)
            f_mono  = tk.font.Font(family="Consolas",  size=10)
        except Exception:
            import tkinter.font as tkfont
            f_title = tkfont.Font(size=14, weight="bold")
            f_label = tkfont.Font(size=10)
            f_mono  = tkfont.Font(size=10)

        tk.Label(root, text="🔒 Trial Expired", font=f_title,
                 bg="#0f172a", fg="#ef4444").pack(pady=(28, 4))
        tk.Label(root, text=f"Your trial for  \"{_SP_APP_NAME}\"  has expired.",
                 font=f_label, bg="#0f172a", fg="#94a3b8").pack(pady=(0, 18))

        # HW ID display
        frm_hw = tk.Frame(root, bg="#1e293b", bd=0)
        frm_hw.pack(fill="x", padx=36, pady=4)
        tk.Label(frm_hw, text="Your Hardware ID:", font=f_label,
                 bg="#1e293b", fg="#94a3b8").pack(anchor="w", padx=12, pady=(10, 0))
        hw_var = tk.StringVar(value=hwid)
        hw_entry = tk.Entry(frm_hw, textvariable=hw_var, font=f_mono,
                            bg="#0f172a", fg="#6366f1", relief="flat",
                            state="readonly", readonlybackground="#0f172a",
                            width=24, bd=0)
        hw_entry.pack(padx=12, pady=(2, 10))

        # Form
        frm_form = tk.Frame(root, bg="#0f172a")
        frm_form.pack(fill="x", padx=36, pady=8)
        for lbl_text in ("Email Address:", "License Key:"):
            tk.Label(frm_form, text=lbl_text, font=f_label,
                     bg="#0f172a", fg="#94a3b8").pack(anchor="w", pady=(8, 2))
            e = tk.Entry(frm_form, font=f_label, bg="#1e293b", fg="#f1f5f9",
                         relief="flat", bd=4, insertbackground="#f1f5f9")
            e.pack(fill="x", ipady=6)
            if lbl_text.startswith("Email"):
                email_entry = e
            else:
                key_entry = e

        status_var = tk.StringVar()
        tk.Label(root, textvariable=status_var, font=f_label,
                 bg="#0f172a", fg="#ef4444").pack(pady=(4, 0))

        def activate():
            em = email_entry.get().strip()
            k  = key_entry.get().strip()
            if not em or not k:
                status_var.set("Please fill in both fields.")
                return
            if _sp_valid(em, hwid, k):
                _sp_write(_SP_LIC_FILE, {"email": em, "key": k})
                result[0] = True
                root.destroy()
            else:
                status_var.set("❌  Invalid license key. Please check and try again.")

        btn = tk.Button(root, text="  Activate License  ", font=f_label,
                        bg="#6366f1", fg="#ffffff", relief="flat", cursor="hand2",
                        activebackground="#818cf8", activeforeground="#ffffff",
                        command=activate)
        btn.pack(pady=14)
        tk.Label(root, text="Purchase a license at  www.maxtechfix.com",
                 font=f_label, bg="#0f172a", fg="#475569").pack(pady=(0, 10))

        root.mainloop()
    except Exception:
        pass
    return result[0]

# ── Main check ────────────────────────────────────────────────────────────────
def _sp_check():
    hwid = _sp_hwid()
    lic = _sp_read(_SP_LIC_FILE)
    if lic.get("email") and lic.get("key") and _sp_valid(lic["email"], hwid, lic["key"]):
        return True

    trial = _sp_read(_SP_TR_FILE)
    if not trial.get("install_date"):
        trial = {"install_date": _dt.datetime.now().isoformat()}
        _sp_write(_SP_TR_FILE, trial)

    install_dt = _dt.datetime.fromisoformat(trial["install_date"])
    days_used  = (_dt.datetime.now() - install_dt).days
    days_left  = max(0, _SP_TRIAL_DAYS - days_used)

    if days_left > 0:
        _sp_trial_notice(days_left)
        return True
    return _sp_expired_dialog()

if not _sp_check():
    _sys.exit(0)
# =============================================================================
#  END OF PROTECTION LAYER — Original code follows
# =============================================================================

###ORIGINAL_CODE###
